---
####################################################
# Preparating steps:
#
# Disable DNSStubListener and update resolv.conf
####################################################
- name: Modify resolved.conf to disable DNSStubListener
  ansible.builtin.replace:
    path: /etc/systemd/resolved.conf
    regexp: "^#?DNSStubListener=.*"
    replace: "DNSStubListener=no"
    backup: true
  notify: Restart systemd-resolved

- name: Ensure resolv.conf symlink exists
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  notify: Restart systemd-resolved

- name: "Setup folder for stack"
  ansible.builtin.file:
    path: "/home/{{ host_user }}/{{ container_data }}/pihole"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
  when: jwt_token is defined and stack_not_exists

- name: "Setup sub folders"
  ansible.builtin.file:
    path: "/home/{{ host_user }}/{{ container_data }}/pihole/{{ sub_directory }}"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
  loop:
    - dnsmasq
  loop_control:
    loop_var: sub_directory
