---
- name: Homeserver
  hosts: all
  become: true

  roles:
    - role: system_prepare

    - role: ssh_prepare
      vars:
        ssh_prepare_pub_key_location: "{{ lookup('env','HOME')}}/.ssh/id_maintainer.pub"

    - role: docker

    - role: portainer

    - role: homeassistant_stack
    - role: pihole_stack
    - role: mosquitto_stack

