---
- name: Homeserver
  hosts: all
  become: true

  roles:
    - role: system_prepare

    - role: ssh_prepare
      vars:
        ssh_prepare_pub_key_location: "{{ lookup('env','HOME')}}/.ssh/id_maintainer.pub"

    - role: docker

    - role: paperless_prepare
    - role: homeassistant_prepare
    - role: immich_prepare
    - role: adguard_prepare
    - role: apprise_prepare

    - role: komodo
