[[repo]]
name = "homeserver"
[repo.config]
server = "homie"
git_account = "sbszcz"
repo = "sbszcz/homeserver"

[[stack]]
name = "mosquitto"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/mosquitto"
file_paths = ["compose.yaml"]

[[stack]]
name = "paperless"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/paperless"
file_paths = ["compose.yaml"]

[[stack]]
name = "homeassistant"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/homeassistant"
file_paths = ["compose.yaml"]

[[stack]]
name = "immich"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/immich"
file_paths = ["compose.yaml"]

[[stack]]
name = "adguard"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/adguard"
file_paths = ["compose.yaml"]

[[stack]]
name = "apprise"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/apprise"
file_paths = ["compose.yaml"]

[[stack]]
name = "komodo-apprise-alerter"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/komodo_apprise_alerter"
file_paths = ["compose.yaml"]
environment = """
  APPRISE_HOST=192.168.178.31:8000
  APPRISE_STATELESS_URLS=[[APPRISE_EMAIL_PROVIDER_URL]]
"""

[[alerter]]
name = "apprise"
[alerter.config]
enabled = true
endpoint.type = "Custom"
endpoint.params.url = "http://homie:7000"
alert_types = [
  "StackImageUpdateAvailable",
  "ServerCpu",
  "ServerMem",
  "ServerDisk",
  "StackStateChange",
  "ContainerStateChange",
  "ResourceSyncPendingUpdates"
]

# Caddy erst aktivieren, nachdem AdGuard als DNS in der FritzBox eingetragen
# und *.homie.box aufloest. Zum Aktivieren die folgenden Zeilen entkommentieren.
[[stack]]
name = "caddy"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/caddy"
file_paths = ["compose.yaml"]
