[[repo]]
name = "homeserver"
[repo.config]
server = "homie"
git_account = "sbszcz"
repo = "sbszcz/homeserver"

[[stack]]
name = "mosquitto"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/mosquitto"
file_paths = ["compose.yaml"]

[[stack]]
name = "paperless"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/paperless"
file_paths = ["compose.yaml"]

[[stack]]
name = "homeassistant"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/homeassistant"
file_paths = ["compose.yaml"]

[[stack]]
name = "immich"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/immich"
file_paths = ["compose.yaml"]

[[stack]]
name = "adguard"
deploy = true
[stack.config]
server = "homie"
poll_for_updates = true
linked_repo = "homeserver"
run_directory = "komodo/stacks/adguard"
file_paths = ["compose.yaml"]

# Caddy erst aktivieren, nachdem AdGuard als DNS in der FritzBox eingetragen
# und *.homie.box aufloest. Zum Aktivieren die folgenden Zeilen entkommentieren.
# [[stack]]
# name = "caddy"
# deploy = true
# [stack.config]
# server = "homie"
# poll_for_updates = true
# linked_repo = "homeserver"
# run_directory = "komodo/stacks/caddy"
# file_paths = ["compose.yaml"]
