services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/diskstation/photos:/mnt/photos
      - /mnt/diskstation/immich/upload:/data/upload
      - /mnt/diskstation/immich/library:/data/library
      - /container_data/immich/library/thumbs:/data/thumbs
      - /container_data/immich/library/profile:/data/profile
      - /container_data/immich/library/encoded-video:/data/encoded-video
      - /container_data/immich/library/backups:/data/backups
    ports:
      - "2283:2283"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    secrets:
      - db_password

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /container_data/immich/postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    secrets:
      - db_password

secrets:
  db_password:
    file: /container_data/immich/secrets/db_password

volumes:
  model-cache:
