---
komodo_image_tag: "2"
komodo_port: 9120
komodo_data_dir: "/{{ container_data }}/komodo"
komodo_root_directory: "/{{ container_data }}/komodo"
komodo_title: "Komodo"
komodo_timezone: "Europe/Berlin"
