---
- name: Authenticate and Check stack
  ansible.builtin.include_role: 
    name: portainer_stacks
    tasks_from: authenticate_and_check_stack

- name: "Setup folder '{{ container_data }}' for stack"
  ansible.builtin.file:
    path: "/home/{{ host_user }}/{{ container_data }}/{{ stack_name }}"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
  when: jwt_token is defined and stack_not_exists

- name: "Setup sub folders"
  ansible.builtin.file:
    path: "/home/{{ host_user }}/{{ container_data }}/{{ stack_name }}/{{ sub_directory }}"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
  loop:
    - data
    - log
    - config
  loop_control:
    loop_var: sub_directory
  when: stack_not_exists

- name: Create mosquitto config
  ansible.builtin.copy:
    dest: //home/{{ host_user }}/{{ container_data }}/{{ stack_name }}/config/mosquitto.conf
    content: |
      allow_anonymous true
      listener 1883
    mode: '0644'
    owner: maintainer
    group: maintainer

- name: "Deploy {{ stack_name }}"
  ansible.builtin.include_role:
    name: portainer_stacks
    tasks_from: create_stack
  vars:
    stack_compose: "{{ lookup('ansible.builtin.template', 'mosquitto.yml') }}"
     
