---
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      - /container_data/adguard/work:/opt/adguardhome/work
      - /container_data/adguard/conf:/opt/adguardhome/conf
