---
- name: Create portainer stacks
  ansible.builtin.include_tasks: create_stack.yml
  vars:
    portainer_host: "{{ portainer_api_url }}"
    admin_user: "{{ portainer_admin_user }}"
    admin_password: "{{ portainer_admin_pass }}"
    endpoint_id: "{{ portainer_endpoint_id }}"
    stack_name: "{{ item.name }}"
    stack_compose: "{{ lookup('ansible.builtin.template', role_path + '/templates/' + item.file) }}"
    directories: "{{ item.dirs }}"

  with_items:
    - name: homeassistant
      file: homeassistant.yml
      dirs:
        - config

    - name: pihole
      file: pihole.yml
      dirs:
        - dnsmasq
