---
- name: Ensure groups exists
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - docker
    - "{{ host_user }}"

- name: Ensure operator is created and is in relevant groups
  ansible.builtin.user:
    name: "{{ host_user }}"
    groups:
      - sudo
      - docker
      - users
    append: true

- name: Install packages
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present
    update_cache: true
  become: true

- name: Ensure NFS client services are enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - rpcbind
  become: true
